version: '3.8'
services:
  php-apache-service:
    container_name: cms_frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-database-service
    volumes:
      - ./:/var/www/html/
    ports:
      - '8000:80'
  mysql-database-service:
    container_name: cms_database
    image: mysql
    restart: always
    env_file:
      - ./.env.dev
    volumes:
    - ./my-datavolume:/var/lib/mysql
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mysql-database-service
    depends_on:
      - mysql-database-service
