version: '3.8'
services:
  php-apache-environment:
    container_name: cms_frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-database-environment
    volumes:
      - ./:/var/www/html/
    ports:
      - '8080:80'
  mysql-database-environment:
    container_name: cms_database
    image: mysql
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "9906:3306"

